route:
  receiver: 'slack'

receivers:
  - name: 'slack'
#    slack_configs:
#      - send_resolved: true
#        username: 'rohithkp'
#        channel: '#alerts'
#        api_url: 'https://hooks.slack.com/services/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'
